[package]
name = "bgpfu"
version = "0.1.0-alpha.1"
edition = "2021"
authors = ["Ben Maddison <benm@workonline.africa>"]
description = "A toolset for working with IRR data"
license = "MIT"
repository = "https://github.com/bgpfu/bgpfu-rs"
readme = "README.md"
keywords = ["irr", "rpsl", "bgp"]
categories = ["network-programming", "database"]

[dependencies]
anyhow = "^1.0"
clap = {version = "^4.0", features = ["derive"]}
irrc = "0.1.0-rc.5"
generic-ip = "0.1.0-rc.2"
log = "^0.4"
rpsl = "0.1.0-rc.1"
simple_logger = {version = "^1.13", features = ["stderr"]}
thiserror = "^1.0"

[dev-dependencies]
version-sync = "^0.9"
