all-features = true

[licenses]
copyleft = "deny"
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
]
confidence-threshold = 0.8
exceptions = [
    { name = "ring", allow = ["OpenSSL"] },
    { name = "option-ext", allow = ["MPL-2.0"] },
    { name = "unicode-ident", allow = ["Unicode-DFS-2016"] },
]

[[licenses.clarify]]
name = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
